const MESSAGE_TYPES = {
  TEXT: 'TEXT',
  LOCATION: 'LOCATION',
  IMAGE: 'IMAGE',
  VOICE: 'VOICE',
  UNKNOWN: 'UNKNOWN'
};

const STATES = {
  START: 'START',
  LANGUAGE_SELECTION: 'LANGUAGE_SELECTION',
  WAITING_FOR_GAT_SELECTION: 'WAITING_FOR_GAT_SELECTION',
  WAITING_FOR_CROP: 'WAITING_FOR_CROP',
  WAITING_FOR_LOCATION: 'WAITING_FOR_LOCATION',
  WAITING_FOR_IMAGE: 'WAITING_FOR_IMAGE',
  READY_FOR_VALIDATION: 'READY_FOR_VALIDATION',
  VALIDATING: 'VALIDATING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

const LANGUAGES = {
  MR: 'mr',
  HI: 'hi',
  EN: 'en'
};

module.exports = {
  MESSAGE_TYPES,
  STATES,
  LANGUAGES
};
