/**
 * Generates the placeholder .wav files in assets/voice/.
 *
 * THESE ARE NOT MARATHI SPEECH. Each file is a short distinguishable tone pattern
 * standing in for a recording that has to be made by a person. They exist so the
 * voice rung of the escalation ladder can be demonstrated end to end — Twilio
 * fetches a real audio file over a real call — without shipping fake "Marathi
 * audio" that would misrepresent what has been built.
 *
 * Committed rather than generated at boot so the demo has no build step, and
 * generated by a script rather than hand-added as binaries so anyone can see
 * exactly what is in them.
 *
 * Replacing them with real recordings: record each script in VOICE_ASSETS
 * (src/services/notifications/voiceMessages.js), export as 8 kHz mono 16-bit PCM
 * WAV — Twilio's telephony sample rate — and overwrite the file of the same name.
 * No code changes are needed.
 *
 * Usage: node scripts/generatePlaceholderVoiceAudio.js
 */
const fs = require('fs');
const path = require('path');
const { VOICE_ASSETS } = require('../src/services/notifications/voiceMessages');

// Twilio downsamples everything to 8 kHz mono for the PSTN, so encoding at the
// telephony rate up front avoids a resample and keeps the files tiny.
const SAMPLE_RATE = 8000;
const BITS_PER_SAMPLE = 16;
const CHANNELS = 1;

// One recognisable pattern per notification type, so a listener can tell which
// message a call was carrying. Frequencies sit in the 300–3400 Hz band the phone
// network actually passes.
const TONE_PATTERNS = {
  DEADLINE_REMINDER: [
    { freq: 880, ms: 400 }, { freq: 0, ms: 150 },
    { freq: 880, ms: 400 }, { freq: 0, ms: 150 },
    { freq: 660, ms: 700 },
  ],
  CALAMITY_RELIEF: [
    { freq: 520, ms: 700 }, { freq: 0, ms: 120 },
    { freq: 780, ms: 700 }, { freq: 0, ms: 120 },
    { freq: 1040, ms: 700 },
  ],
  SUBMISSION_REVIEW: [
    { freq: 1200, ms: 250 }, { freq: 0, ms: 120 },
    { freq: 900, ms: 250 }, { freq: 0, ms: 120 },
    { freq: 1200, ms: 250 }, { freq: 0, ms: 120 },
    { freq: 900, ms: 900 },
  ],
};

const DEFAULT_PATTERN = [{ freq: 800, ms: 500 }, { freq: 0, ms: 200 }, { freq: 600, ms: 500 }];

/** Renders a tone list to 16-bit signed PCM samples. */
function renderPcm(pattern) {
  const chunks = [];

  for (const { freq, ms } of pattern) {
    const sampleCount = Math.round((ms / 1000) * SAMPLE_RATE);
    const buffer = Buffer.alloc(sampleCount * 2);

    for (let i = 0; i < sampleCount; i += 1) {
      let value = 0;

      if (freq > 0) {
        // Amplitude at ~40% of full scale: audible over a phone line without
        // clipping once the carrier applies its own gain.
        const amplitude = 0.4 * 32767;
        // Linear fade over 5 ms at each end. Without it the abrupt start clicks,
        // and some codecs turn that click into a burst of noise.
        const fadeSamples = Math.min(Math.round(0.005 * SAMPLE_RATE), Math.floor(sampleCount / 2));
        const fade = fadeSamples === 0
          ? 1
          : Math.min(i / fadeSamples, (sampleCount - 1 - i) / fadeSamples, 1);

        value = Math.round(amplitude * fade * Math.sin((2 * Math.PI * freq * i) / SAMPLE_RATE));
      }

      buffer.writeInt16LE(value, i * 2);
    }

    chunks.push(buffer);
  }

  return Buffer.concat(chunks);
}

/** Wraps PCM samples in a canonical 44-byte RIFF/WAVE header. */
function wrapWav(pcm) {
  const byteRate = (SAMPLE_RATE * CHANNELS * BITS_PER_SAMPLE) / 8;
  const header = Buffer.alloc(44);

  header.write('RIFF', 0, 'ascii');
  header.writeUInt32LE(36 + pcm.length, 4);
  header.write('WAVE', 8, 'ascii');
  header.write('fmt ', 12, 'ascii');
  header.writeUInt32LE(16, 16);           // fmt chunk size
  header.writeUInt16LE(1, 20);            // PCM
  header.writeUInt16LE(CHANNELS, 22);
  header.writeUInt32LE(SAMPLE_RATE, 24);
  header.writeUInt32LE(byteRate, 28);
  header.writeUInt16LE((CHANNELS * BITS_PER_SAMPLE) / 8, 32); // block align
  header.writeUInt16LE(BITS_PER_SAMPLE, 34);
  header.write('data', 36, 'ascii');
  header.writeUInt32LE(pcm.length, 40);

  return Buffer.concat([header, pcm]);
}

function generate() {
  const outDir = path.join(__dirname, '..', 'assets', 'voice');
  fs.mkdirSync(outDir, { recursive: true });

  const written = [];

  for (const [type, asset] of Object.entries(VOICE_ASSETS)) {
    const wav = wrapWav(renderPcm(TONE_PATTERNS[type] || DEFAULT_PATTERN));
    const target = path.join(outDir, asset.file);
    fs.writeFileSync(target, wav);
    written.push({ type, file: asset.file, bytes: wav.length });
  }

  return written;
}

if (require.main === module) {
  const written = generate();
  console.log('Placeholder voice assets written (tones, NOT Marathi speech):');
  for (const { type, file, bytes } of written) {
    console.log(`  ${file.padEnd(28)} ${type.padEnd(20)} ${bytes} bytes`);
  }
}

module.exports = { generate, renderPcm, wrapWav, TONE_PATTERNS, SAMPLE_RATE };
